#!/usr/bin/env bash
# Usage: envdev newsub <command>
# Summary: Create a new .sub directory in the current directory and with the specified command
# Help: no help yet

set -e

if [ "$1" = "" ]; then
    echo "No command specified"
    envdev help newsub
    exit
fi

echo "Cloning sub github repository to .sub..."
git clone http://github.com/37signals/sub.git .sub
cd .sub
echo "Customising the repo for command $1"
./prepare.sh $1 > /dev/null

rm -rf .git
./bin/$1 init
echo "Done"
